version: '3'
services:
  db:
    container_name: e_assignment_db
    image: postgres:12
    restart: always
    ports:
      - '5435:5432'
    environment:
      - POSTGRES_DB=e_assignment
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgresPass
    volumes:
#      - ./_db:/var/lib/postgresql/data
      - ./_db_init:/docker-entrypoint-initdb.d
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    entrypoint: ["./wait-for-it.sh", "-s" ,"-t", "20", "e_assignment_db:5432", "--"]
    command: ["./_dist/app"]
    ports:
      - '8080:8080'
